### ISSUE TITLE
Error Mounting

### ISSUE THREAD

**Issue by alfonsoletizia1** [arduino-libraries/Arduino_MKRMEM#16]
Hi, I'm trying to run the example SPIFFSFormat, but I'm stucked with the mount error: 

mount() failed with error code-10025.

This occurs after the format. Any advise? I'm using an Arduino nano RP2040 and an MKR MEM Shield v2.

Thanks, AL

**Comment by aentinger** [comment]
Hi @alfonsoletizia1 :coffee: :wave:

This should not happen. Can you please provide the full output of `SPIFFSFormat.ino`?

**Comment by alfonsoletizia1** [comment]
Here the output: 
 Erasing chip ...
 Mounting ...
 Unmounting ...
 Formatting ...
 Mounting ...
 mount() failed with error code 
 -10025
![error_spiffs](https://user-images.githubusercontent.com/62029605/140886154-47426ee0-8f54-4f11-9902-7455dd9814f4.PNG)

**Comment by aentinger** [comment]
Most curious. If your wiring would be wrong, you should fail much earlier. Possibly the SPI clocks are too high and don't do well with your wired setup. Can you try and [change those lines](https://github.com/arduino-libraries/Arduino_MKRMEM/blob/master/src/Arduino_W25Q16DV.cpp#L29-L34) to much lower SPI speeds, i.e. 5 MHz for both.

**Comment by alfonsoletizia1** [comment]
Great, I've tried the SPI configuration and I'm not getting the mount error anymore.

Thank you!
